export const propertyConstants = {
  CREATE_REQUEST: 'PROPERTY_CREATE_REQUEST',
  CREATE_SUCCESS: 'PROPERTY_CREATE_SUCCESS',
  CREATE_FAILURE: 'PROPERTY_CREATE_FAILURE',


  GETALL_REQUEST: 'PROPERTY_GETALL_REQUEST',
  GETALL_SUCCESS: 'PROPERTY_GETALL_SUCCESS',
  GETALL_FAILURE: 'PROPERTY_GETALL_FAILURE',

  DELETE_REQUEST: 'PROPERTY_DELETE_REQUEST',
  DELETE_SUCCESS: 'PROPERTY_DELETE_SUCCESS',
  DELETE_FAILURE: 'PROPERTY_DELETE_FAILURE',
};
